services:
  - type: web
    name: veggie-village
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /index.php
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: APP_URL
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: APP_DEBUG
        value: "false"
